data:
  input_dir: /home/username/data/DAVIS
  output_dir: /home/username/data/DAVIS
  REFERENCES : [5, 10, 20, 25, 30]
  METHODS : ['random', 'cubic', 'hopper', 'atomic']
  methods : ['random', 'cubic', 'hopper']
  SIZES : [50000, 100000, 200000, 300000]
  REPS : [0, 1, 2, 3, 4]
  label_key : 'celltype'

  